//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papeleria_Patio_Colombia.Capa_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Papeleria_Patio_ColombiaEntities2 : DbContext
    {
        public Papeleria_Patio_ColombiaEntities2()
            : base("name=Papeleria_Patio_ColombiaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ordenes> Ordenes { get; set; }
        public virtual DbSet<Receptor> Receptor { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
    }
}
