//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papeleria_Patio_Colombia.Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        public int id_Ordenes { get; set; }
        public int Id_Servicios { get; set; }
        public string Empleado { get; set; }
    
        public virtual Receptor Receptor { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
