//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papeleria_Patio_Colombia.Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public int Id_Servicios { get; set; }
        public string Descripcion { get; set; }
        public int Codigo { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
    }
}
